### PR TITLE
RE: issue #7 replace getMemory() with os.totalmem() #10

### PR DESCRIPTION
**Pull request by toddmcintire**
I tried searching for a way to add commits to your PR and it seems I can't unless I have write access, but the other way is to just submit a PR to your fork which will update the original PR. Giving us both credit for working on this together!😃

### CODE REVIEW

**Comment by adrianmarinwork** [comment]
Oh I'm sorry I didn't see the message nor the pull request, I thought that you would merge my pull request to your repo.
What do you want to do?

**Comment by toddmcintire** [comment]
That's quite alright, no rush here. I interpreted your earlier message of preferring the math solution to mean that was the intended direction we wanted to take the PR. So I submitted this PR which if merged should update the original PR with the math variant so we both get credit for the work as opposed to me just accepting my math branch.

**Comment by adrianmarinwork** [comment]
Ohhh I get it, I'm new in this world of github and helping people with their issues. If you want I can accept the PR and then you accept mine, this way as you said we both get credit.
If not don't worry, keep working and I'll delete my PR, it was a pretty small thing. 👍

**Comment by toddmcintire** [comment]
Let's do it! 😄

**Pull request merged**
